[project]
name = "stormy-ai"
version = "1.0.1a9"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Cozmo", email = "107803920+Cozmo18@users.noreply.github.com" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy<2",
    "torch==2.2.2",
    "datasets>=4.0.0",
    "jsonargparse[signatures]>=4.40.0",
    "transformers==4.49",
    "lightning>=2.5.0",
    "rich==14.0",
    "tensorboard>=2.20.0",
    "pydantic>=2.11.7",
    "litserve>=0.2.15",
]

[project.scripts]
stormy = "stormy:main"
trainer = "stormy.trainer:cli_main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/stormy"]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "ruff>=0.12.5",
    "ty>=0.0.1a16",
]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle (error)
    "W",   # pycdoestyle (warnings)
    "F",   # pyflakes
    "B",   # bugbear
    "B9",
    "C4",  # flake8-comprehensions
    "SIM", # flake8-simplify
    "I",   # isort
    "UP",  # pyupgrade
    "PIE", # flake8-pie
    "PGH", # pygrep-hooks
    "PYI", # flake8-pyi
    "RUF",
]

ignore = [
    # only relevant if you run a script with `python -0`,
    # which seems unlikely for any of the scripts in this repo
    "B011",
    # Leave it to the formatter to split long lines and
    # the judgement of all of us.
    "E501",
]

[tool.ty.environment]
python = "./.venv"
